server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/textroad
    username: root
    password: root

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

