server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/koaladb
    username: root
    password: root

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

  security:
    user:
      name: user
      password: 1111